In [38]:
import pandas as pd

In [39]:
from google.colab import drive
drive.mount('/content/drive')
df = pd.read_csv('/content/drive/MyDrive/dataset/global_pharmacy_sales_2020_2025_daily_dataset.csv')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [40]:
df.size

2491860

In [41]:
df.shape

(177990, 14)

In [42]:
df.head()
df.info()
df.columns

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 177990 entries, 0 to 177989
Data columns (total 14 columns):
 #   Column                 Non-Null Count   Dtype
---  ------                 --------------   -----
 0   date                   177990 non-null  object
 1   year                   177990 non-null  int64
 2   month                  177990 non-null  int64
 3   day                    177990 non-null  int64
 4   region                 177990 non-null  object
 5   country                177990 non-null  object
 6   category               177990 non-null  object
 7   medicine               177990 non-null  object
 8   age_group              177990 non-null  object
 9   units_sold             177990 non-null  int64
 10  unit_price             177990 non-null  float64
 11  stock_level            177990 non-null  int64
 12  expiry_days_remaining  177990 non-null  int64
 13  covid_flag             177990 non-null  int64
dtypes: float64(1), int64(7), object(6)
memory usage: 19.0+ MB

Index(['date', 'year', 'month', 'day', 'region', 'country', 'category',
       'medicine', 'age_group', 'units_sold', 'unit_price', 'stock_level',
       'expiry_days_remaining', 'covid_flag'],
      dtype='object')

In [43]:
df.describe()

,year,month,day,units_sold,unit_price,stock_level,expiry_days_remaining,covid_flag
count,177990.000000,177990.000000,177990.000000,177990.000000,177990.000000,177990.000000,177990.000000,177990.000000
mean,2022.499702,6.521754,15.730457,447.913849,52.554729,4552.991780,374.038109,0.333519
std,1.708113,3.448703,8.801170,338.924528,27.421909,346.608511,199.759193,0.471471
min,2020.000000,1.000000,1.000000,31.000000,5.000000,0.000000,30.000000,0.000000
25%,2021.000000,4.000000,8.000000,284.000000,28.770000,4443.000000,200.000000,0.000000
50%,2023.000000,7.000000,16.000000,387.000000,52.600000,4598.000000,374.000000,0.000000
75%,2024.000000,10.000000,23.000000,529.000000,76.310000,4735.000000,547.000000,1.000000
max,2025.000000,12.000000,31.000000,8704.000000,100.000000,5124.000000,720.000000,1.000000

In [44]:
df.isnull().sum()

date                     0
year                     0
month                    0
day                      0
region                   0
country                  0
category                 0
medicine                 0
age_group                0
units_sold               0
unit_price               0
stock_level              0
expiry_days_remaining    0
covid_flag               0
dtype: int64

In [45]:
df.duplicated().sum()

np.int64(2630)

In [46]:
df['date'] = pd.to_datetime(df['date'])

In [47]:
df.dtypes

date                     datetime64[ns]
year                              int64
month                             int64
day                               int64
region                           object
country                          object
category                         object
medicine                         object
age_group                        object
units_sold                        int64
unit_price                      float64
stock_level                       int64
expiry_days_remaining             int64
covid_flag                        int64
dtype: object

In [48]:
df.isnull().sum()

date                     0
year                     0
month                    0
day                      0
region                   0
country                  0
category                 0
medicine                 0
age_group                0
units_sold               0
unit_price               0
stock_level              0
expiry_days_remaining    0
covid_flag               0
dtype: int64

In [49]:
df.drop_duplicates(inplace=True)

In [70]:
from sklearn.preprocessing import LabelEncoder
encoder = LabelEncoder()
cols = ['region','country','category','medicine','age_group']
for col in cols:
    df[col] = encoder.fit_transform(df[col])